export { map } from './collection/map'
export { flow } from './flow'
export { update } from './object/update'
export { head } from './array/head'
export { tail } from './array/tail'
export { take } from './array/take'
export { drop } from './array/drop'
